
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'inform_risks'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'inform_risks'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Models configuration
models:
  inform_risks:
    stg:
      +materialized: view
      +schema: stg
    ods:
      +materialized: table
      +schema: ods
    prs:
      +materialized: table
      general:
        +schema: general
      hazard_exposure:
        +schema: hazard_exposure
      vulnerability:
        +schema: vulnerability
      lack_of_coping_capacity:
        +schema: lack_of_coping_capacity
