version: '3'

services:

  analytics_engineering_demo:
    image: brocolidata/analytics_engineering_demo
    build: .
    container_name: analytics_engineering_demo
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-exampleuser}
      POSTGRES_PASSWORD: ${POSTGRESz_PASSWORD:-Examplepassword}
      POSTGRES_DB: ${POSTGRES_DB:-dwh_db}
      DBT_PROFILES_DIR: /AE_demo/src/profiles
    volumes:
      - ../:/AE_demo
    working_dir: /AE_demo
    stdin_open: true
    tty: true

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-exampleuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Examplepassword}
      POSTGRES_DB: ${POSTGRES_DB:-dwh_db}
    volumes:
      - dwh_data:/var/lib/postgresql/data

volumes:
  dwh_data: