version: 2

sources:
  - name: inform
    description: >
      INFORM est une collaboration du Groupe de référence du Comité permanent inter-agences sur les risques, 
      l'alerte précoce et la préparation et la Commission européenne.
      
      L'indice de risque INFORM est une évaluation mondiale et open source des risques pour les crises humanitaires et les catastrophes. 
      Il peut appuyer les décisions en matière de prévention, de préparation et d'intervention.

      Source : [DRMKC INFORM](https://drmkc.jrc.ec.europa.eu/inform-index/INFORM-Risk/Results-and-data/moduleId/1782/id/453/controller/Admin/action/Results)


    schema: raw
    tables:
      - name: inform_trends
        description: >
          L'indice de risque global INFORM identifie les pays à risque de crises humanitaires 
          et de catastrophes qui pourraient dépasser la capacité de réponse nationale. 

          Il se compose de trois dimensions 
          - les dangers et l'exposition 
          - la vulnérabilité
          - le manque de capacité d'adaptation.
        columns:
          - name: iso3
            description: "Code ISO3 (identifiant unique) de la zone géographique concernée par le score de l'indicateur"
          - name: indicatorid
            description: "Identifiant Unique de l'indicateur"
          - name: indicatorname
            description: "Nom de l'indicateur"
          - name: indicatorscore
            description: "Score de l'indicateur"
          - name: surveyyear
            description: "Année de l'étude (à ignorer)"
          - name: indicator type
            description: "Type d'indicateur"
          - name: informyear
            description: "Année du Score de l'Indicateur"
      - name: inform_countries
        description: "Zones géographiques d'INFORM"
        columns:
          - name: continent
            description: "Continent de la zone géographique (à retirer car vide)"
          - name: categorytype
            description: >
              Hiérarchie géographique. Correspondances des valeurs : 
                
              - ADMIN    : Région du monde

              - ADMIN0   : Pays

              - ADMIN1   : Région d'un pays

              - REGION_0 : Valeurs diverses (à retirer)

              - REGION_1 : Départements divers (à retirer)

              - REGION_2 : Municipalités
          - name: adminlevel
            description: "Niveau administratif (à retirer car vide)"
          - name: categoryinfo
            description: "Informations sur la catégorie (à retirer car peu utile)"
          - name: incomevalue
            description: "Niveau de revenu du pays (à retirer car vide)"
          - name: notes
            description: "Notes sur le pays (à retirer car vide)"
          - name: iso3
            description: "Code ISO3 (identifiant unique) de la zone géographique"
          - name: countryname
            description: "Nom de la zone géographique"
          - name: isogroup
            description: "Parent de la zone géographique"